### ISSUE TITLE
 [ERROR] Cannot load resource...

### ISSUE THREAD

**Issue by pylearn2030** [lnNgyn1/PeriodInsertBundle#2] opened 2024-03-11 08:57 UTC
Dear,
I got an error occurred while rebuilding cache PeriodInsertBundle...
 ++++++++
 Rebuilding your cache, please be patient ...
 // Clearing the cache for the prod environment with debug
 // false
 [ERROR] Cannot load resource "../../Controller/". Make sure there is a loader
         supporting the "attribute" type.
Could you please help me to check this error?
Many thanks and best regards!
Py.
![Error rebuilding PeriodInsertBundle](https://github.com/lnNgyn1/PeriodInsertBundle/assets/162970815/5cbdfd86-50b5-42eb-a41c-18d70f007ae9)

**Comment by pylearn2030** [comment] 2024-03-11 09:03
![Error rebuilding PeriodInsertBundle](https://github.com/lnNgyn1/PeriodInsertBundle/assets/162970815/8764de53-f945-4554-95a9-c336dd1c0186)

**Comment by lnNgyn1** [comment] 2024-03-13 14:52
Hi, thanks for opening this issue! I'll check this error right away and get back to you as soon as possible.

**Comment by lnNgyn1** [comment] 2024-03-13 15:30
I can't reproduce the error, what is your Kimai setup? What version are you using, and are you using Docker?

**Comment by pylearn2030** [comment] 2024-03-14 07:57
Many thanks for your reply! I am using Kimai 1.3
I upgraded it to Kimai 2.0 and I can install this plugin to Kimai 2.0
Thank you again!

**Comment by lnNgyn1** [comment] 2024-03-14 15:39
I see, on a fresh installation of Kimai 2.0 reloading the cache works fine. Let me test the plugin when upgrading from old versions of Kimai.

EDIT: This issue was resolved by upgrading from Kimai 1.3 to Kimai 2.0. Refer to this [issue](https://github.com/kimai/kimai/issues/4698).

**Closed as completed** 2024-08-19 21:50 UTC
Labels: bug
